# https://numtide.github.io/devshell
[[commands]]
package = "_1password"
category = "general commands"

[[commands]]
package = "azure-cli"
category = "general commands"

[[commands]]
package = "docker"
category = "general commands"

[[commands]]
package = "docker-compose"
category = "general commands"

[[commands]]
package = "postgresql"
category = "Data Science"

[[commands]]
package = "python3"
category = "Data Science"

[[commands]]
package = "poetry"
category = "Data Science"

[devshell]
packages = [
  "libstdcxx5",
  "zlib",
  "gcc",
  "glib"
]


[[env]]
name = "PYTHON_KEYRING_BACKEND"
value = "keyring.backends.null.Keyring"

