[tool.poetry]
name = "scientific_test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "*"
pandas = "*"


[build-system]
requires = ["poetry-core>=1.1"]
build-backend = "poetry.core.masonry.api"
